### ISSUE TITLE
python 3.5下报错

### ISSUE THREAD

**Issue by xyz1001** [xyz1001/dotfilesmanager#4]
```
~# dfm -h
Traceback (most recent call last):
  File "/usr/local/bin/dfm", line 7, in <module>
    from dfm import main
  File "/usr/local/lib/python3.5/dist-packages/dfm.py", line 40, in <module>
    dotfiles_root = os.path.join(*[Path.home(), "dotfiles"])
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

**Comment by xyz1001** [comment]
使用os.path代替pathlib
